Repository ing-bank/baker, pull requests merged in 2024-10, with the labels that each got.

#1686 Fixed the Date conversion for the Baker HTTP dashboard.
  http/baker-http-dashboard/README.md
  http/baker-http-dashboard/src/app/baker-conversion.service.ts
Labels: bug

#1767 Added checkpointevents for subrecipes in compiler.
  core/recipe-compiler/src/main/scala/com/ing/baker/compiler/RecipeCompiler.scala
  core/recipe-compiler/src/test/java/RecipeCompilerTests.java
Labels: feature

#1782 fix CI pipeline for the pull requests from forks (i.e. scala-steward) excluding publish jobs
  .github/workflows/ci.yml
Labels: chore

#1781 Patch updates
  .github/workflows/ci.yml
  build.sbt
  project/Dependencies.scala
  project/plugins.sbt
Labels: dependency

#1772 Update sbt-scalafix to 0.13.0
  project/plugins.sbt
Labels: dependency

#1775 Update netty-handler to 4.1.114.Final
  project/Dependencies.scala
Labels: dependency

#1792 Exposes methods/functions to allow for re-use.
  bakery/state/src/main/scala/com/ing/bakery/AkkaBakery.scala
  bakery/state/src/main/scala/com/ing/bakery/ClosableBakery.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/AkkaBaker.scala
  http/baker-http-server/src/main/scala/com/ing/baker/http/server/scaladsl/Http4sBakerServer.scala
Labels: enhancement
