Repository ing-bank/baker, pull requests merged in 2024-11, with the labels that each got.

#1793 Update jackson-core, jackson-databind to 2.18.1
  project/Dependencies.scala
Labels: dependency

#1799 Exposed the parseEventRequest method to the deserialisation so it can be reused
  http/baker-http-server/src/main/scala/com/ing/baker/http/server/javadsl/BakerWithHttpResponse.scala
Labels: enhancement

#1801 Patch updates
  project/build.properties
Labels: dependency

#1804 Bugfix for the in-memory baker stop execution. It sometimes stopped mid execution.
  core/baker-interface/src/main/scala/com/ing/baker/runtime/model/recipeinstance/TransitionExecution.scala
Labels: bug

#1805 Update spring-context, spring-core to 6.2.0
  project/Dependencies.scala
Labels: dependency
