Repository ing-bank/baker, pull requests merged in 2025-03, with the labels that each got.

#1843 Patch updates
  project/Dependencies.scala
  project/build.properties
Labels: dependency

#1844 upgrade paranamer to 2.8.3 which fixes the broken API change in 2.8.1
  project/Dependencies.scala
Labels: dependency

#1849 adjust CI pipeline to publish to azure for pull requests as well
  .github/workflows/ci.yml
Labels: chore

#1847 Patch updates
  project/Dependencies.scala
  project/plugins.sbt
Labels: dependency

#1848 allow deactivating recipes
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/AkkaBaker.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_index/ProcessIndex.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/recipe_manager/ActorBasedRecipeManager.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/recipe_manager/DefaultRecipeManager.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/recipe_manager/PollingAware.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/recipe_manager/RecipeManager.scala
  core/akka-runtime/src/test/java/com/ing/baker/BakerTest.java
  core/akka-runtime/src/test/java/com/ing/baker/Webshop.java
  core/akka-runtime/src/test/scala/com/ing/baker/runtime/recipe_manager/ActorBasedRecipeManagerSpec.scala
  core/akka-runtime/src/test/scala/com/ing/baker/runtime/recipe_manager/DefaultRecipeManagerSpec.scala
  core/akka-runtime/src/test/scala/com/ing/baker/runtime/recipe_manager/PollingAwareSpec.scala
  core/akka-runtime/src/test/scala/com/ing/baker/runtime/recipe_manager/RecipeManagerActorImplSpec.scala
  core/baker-interface-kotlin/src/main/kotlin/com/ing/baker/runtime/kotlindsl/Baker.kt
  core/baker-interface/src/main/scala/com/ing/baker/runtime/common/Baker.scala
  core/baker-interface/src/main/scala/com/ing/baker/runtime/javadsl/Baker.scala
  core/baker-interface/src/main/scala/com/ing/baker/runtime/model/BakerF.scala
  core/baker-interface/src/main/scala/com/ing/baker/runtime/model/RecipeManager.scala
  core/recipe-compiler/src/test/java/RecipeCompilerTests.java
  http/baker-http-client/src/main/scala/com/ing/baker/http/client/scaladsl/BakerClient.scala
  http/baker-http-dashboard/src/app/bakery.service.ts
  http/baker-http-dashboard/src/app/recipes/recipes.component.html
  http/baker-http-dashboard/src/app/recipes/recipes.component.ts
  http/baker-http-server/src/main/scala/com/ing/baker/http/server/scaladsl/Http4sBakerServer.scala
Labels: feature
