Repository ing-bank/baker, pull requests merged in 2025-06, with the labels that each got.

#1877 Update junit-jupiter-engine to 5.13.0
  project/Dependencies.scala
Labels: dependency

#1882 Update netty-handler to 4.2.2.Final
  project/Dependencies.scala
Labels: dependency

#1876 WIP: FireEventAfterFailure retry strategy
  bakery/state/src/main/scala/com/ing/bakery/components/EventSink.scala
  core/akka-runtime/src/main/protobuf/process_instance.proto
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/AkkaBaker.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/delayed_transition_actor/DelayedTransitionActor.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_index/ProcessIndex.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_instance/ProcessInstance.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_instance/ProcessInstanceEventSourcing.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_instance/ProcessInstanceProto.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_instance/ProcessInstanceProtocol.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_instance/ProcessInstanceSerialization.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_instance/internal/ExceptionStrategy.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/serialization/BakerTypedProtobufSerializer.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/internal/RecipeRuntime.scala
  core/akka-runtime/src/test/scala/com/ing/baker/AllTypeRecipe.scala
  core/akka-runtime/src/test/scala/com/ing/baker/BakerRuntimeTestBase.scala
  core/akka-runtime/src/test/scala/com/ing/baker/runtime/akka/BakerExecutionSpec.scala
  core/akka-runtime/src/test/scala/com/ing/baker/runtime/akka/actor/process_index/SensoryEventResponseHandlerSpec.scala
  core/akka-runtime/src/test/scala/com/ing/baker/runtime/akka/actor/process_instance/ProcessInstanceSpec.scala
  core/baker-interface/src/main/protobuf/common.proto
  core/baker-interface/src/main/scala/com/ing/baker/runtime/model/BakerF.scala
  core/baker-interface/src/main/scala/com/ing/baker/runtime/model/recipeinstance/RecipeInstance.scala
  core/baker-interface/src/main/scala/com/ing/baker/runtime/model/recipeinstance/RecipeInstanceState.scala
  core/baker-interface/src/main/scala/com/ing/baker/runtime/serialization/protomappings/BakerEventMapping.scala
  core/baker-interface/src/main/scala/com/ing/baker/runtime/serialization/protomappings/InteractionFailureStrategyMapping.scala
  core/baker-interface/src/test/scala/com/ing/baker/runtime/serialization/JsonDecodersSpec.scala
  core/baker-interface/src/test/scala/com/ing/baker/runtime/serialization/JsonEncodersSpec.scala
  core/intermediate-language/src/main/scala/com/ing/baker/il/failurestrategy/ExceptionStrategyOutcome.scala
  core/intermediate-language/src/main/scala/com/ing/baker/il/failurestrategy/FireFunctionalEventAfterFailure.scala
  core/intermediate-language/src/main/scala/com/ing/baker/il/failurestrategy/RetryWithIncrementalBackoff.scala
  core/intermediate-language/src/main/scala/com/ing/baker/il/package.scala
  core/intermediate-language/src/test/scala/com/ing/baker/il/failurestrategy/RetryWithIncrementalBackoffSpec.scala
  core/recipe-compiler/src/main/scala/com/ing/baker/compiler/package.scala
  core/recipe-dsl-kotlin/src/main/kotlin/com/ing/baker/recipe/kotlindsl/KotlinDsl.kt
  core/recipe-dsl-kotlin/src/test/kotlin/com/ing/baker/recipe/kotlindsl/KotlinDslTest.kt
  core/recipe-dsl/src/main/scala/com/ing/baker/recipe/common/InteractionFailureStrategy.scala
  core/recipe-dsl/src/main/scala/com/ing/baker/recipe/javadsl/InteractionFailureStrategy.scala
  examples/docs-code-snippets/src/main/kotlin/examples/kotlin/recipes/RecipeFireEvent.kt
  examples/docs-code-snippets/src/main/kotlin/examples/kotlin/recipes/RecipeWithDefaultFailureStrategy.kt
  examples/docs-code-snippets/src/main/kotlin/examples/kotlin/recipes/RecipeWithFailureStrategy.kt
  examples/docs-code-snippets/src/main/scala/examples/scala/recipes/RecipeWithDefaultFailureStrategy.scala
  examples/docs-code-snippets/src/main/scala/examples/scala/recipes/RecipeWithFailureStrategy.scala
Labels: feature

#1890 Patch updates
  project/Dependencies.scala
Labels: dependency

#1888 Fix the internal index to correctly tag processes as active.
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_index/ProcessIndex.scala
  core/akka-runtime/src/main/scala/com/ing/baker/runtime/akka/actor/process_instance/ProcessInstance.scala
Labels: bug

#1892 Upgrade sbt-ci-release for publishing via the Sonatype Central portal
  project/Publish.scala
  project/plugins.sbt
Labels: enhancement
